//
//  DetailPresenter.swift
//  Simple
//
//  Created by Raymond Law on 6/25/18.
//  Copyright (c) 2018 Clean Swift LLC. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol DetailPresentationLogic
{
  func presentShowGreeting(response: Detail.ShowGreeting.Response)
}

class DetailPresenter: DetailPresentationLogic
{
  weak var viewController: DetailDisplayLogic?
  
  // MARK: Show greeting
  
  func presentShowGreeting(response: Detail.ShowGreeting.Response) {
    let viewModel = Detail.ShowGreeting.ViewModel(userID: response.userID)
    viewController?.displayShowGreeting(viewModel: viewModel)
  }
}
