//
//  DetailInteractor.swift
//  Simple
//
//  Created by Raymond Law on 6/25/18.
//  Copyright (c) 2018 Clean Swift LLC. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol DetailBusinessLogic
{
  func showGreeting(request: Detail.ShowGreeting.Request)
}

protocol DetailDataStore
{
}

class DetailInteractor: DetailBusinessLogic, DetailDataStore
{
  var presenter: DetailPresentationLogic?
  var worker: DetailWorker?
  
  // MARK: Show greeting
  
  func showGreeting(request: Detail.ShowGreeting.Request) {
//    let userID = AuthenticationWorker().getUserID()
//    let response = Detail.ShowGreeting.Response(userID: userID)
//    presenter?.presentShowGreeting(response: response)
  }
}
