//
//  MainViewController.swift
//  Simple
//
//  Created by Raymond Law on 6/25/18.
//  Copyright (c) 2018 Clean Swift LLC. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import SnapKit


protocol MainDisplayLogic: AnyObject {
    var chars: [CharacterModels.Char] { set get }
    //func displayCharacters()
}


class MainViewController: BaseViewController, MainDisplayLogic {    
    var interactor: MainBusinessLogic?
    var router: MainRoutingLogic?
    
    var chars: [CharacterModels.Char] = [] {
        didSet {
            tableView.reloadData()
        }
    }

    // MARK: Setup
  
    override func setup() {
        let viewController = self
        let interactor = MainInteractor()
        let presenter = MainPresenter()
        let router = MainRouter()
        let worker = MainWorker()
        viewController.interactor = interactor
        viewController.router = router
        interactor.presenter = presenter
        interactor.coreDataWorker = worker
        interactor.apiWorker = worker
        presenter.viewController = viewController
        router.viewController = viewController
    }
  
    // MARK: View lifecycle

    override func viewDidLoad() {
        super.viewDidLoad()
        configureUI()
               
        interactor?.checkStateIsEmptyDB()
    }

    // MARK: Configuration -

    private lazy var tableView: UITableView = {
        let tableView = UITableView()
        tableView.backgroundColor = .clear
        tableView.delegate = self
        tableView.dataSource = self
        tableView.rowHeight = 80
        tableView.separatorStyle = .none
        tableView.register(CharTableCell.self, forCellReuseIdentifier: String(describing: CharTableCell.self))
        view.addSubview(tableView)
        return tableView
    }()
    
    private lazy var appearance: UINavigationBarAppearance = {
        let appearance = UINavigationBarAppearance()
        appearance.configureWithOpaqueBackground()
        appearance.backgroundColor = UIColor.gray1
        appearance.titleTextAttributes = [.foregroundColor: UIColor.purple1]
        return appearance
    }()

    private func configureUI() {
        view.backgroundColor = .gray1
        
        navigationItem.title = "List"
        navigationController?.navigationBar.tintColor = .purple1
        navigationController?.navigationBar.standardAppearance = appearance
        navigationController?.navigationBar.scrollEdgeAppearance = appearance
        
        tableView.snp.makeConstraints { make in
            make.top.equalTo(view.safeAreaLayoutGuide).offset(20)
            make.leading.equalToSuperview().offset(20)
            make.trailing.equalToSuperview().offset(-20)
            make.bottom.equalToSuperview().offset(-20)
        }
    }
}

extension MainViewController: UITableViewDelegate, UITableViewDataSource {
    func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        chars.count
    }
    
    func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        guard let cell = tableView
            .dequeueReusableCell(withIdentifier: String(describing: CharTableCell.self), for: indexPath) as? CharTableCell else {
            return UITableViewCell()
        }
        
        let selectedView = UIView()
        selectedView.backgroundColor = .clear
        cell.selectedBackgroundView = selectedView
        
        cell.char = chars[indexPath.row]
        return cell
    }
    
    func tableView(_ tableView: UITableView, willDisplay cell: UITableViewCell, forRowAt indexPath: IndexPath) {
        guard indexPath.row == chars.count - 1 else { return }
        interactor?.loadNextCharacters()
    }
    
    func tableView(_ tableView: UITableView, didSelectRowAt indexPath: IndexPath) {
        tableView.deselectRow(at: indexPath, animated: true)
        let char = chars[indexPath.row]
        router?.showDetail(for: char)
    }
}
