//
//  MainInteractor.swift
//  Simple
//
//  Created by Raymond Law on 6/25/18.
//  Copyright (c) 2018 Clean Swift LLC. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MainBusinessLogic {
    func checkStateIsFirst()
    func showFromDBCharacters()
    func loadNextCharacters()
}

protocol MainDataStore {
}

class MainInteractor: MainBusinessLogic, MainDataStore {
    var presenter: MainPresentationLogic?
    var coreDataWorker: CoreDataWorkerProtocol?
    var apiWorker: ApiWorkerProtocol?
    
    func checkStateIsFirst() {
        if coreDataWorker?.bdIsEmpty == true {
            loadNextCharacters()
        } else {
            showFromDBCharacters()
        }
    }

    func showFromDBCharacters() {
        guard let result = coreDataWorker?.fetchAllChars(),
              let chars = parse(result: result) else { return }
        presenter?.presentFromDB(cdChars: chars)
    }
    
    func loadNextCharacters() {
        Task {
            guard let result = await self.apiWorker?.loadNewChars(),
                  let chars = self.parse(result: result),
                  let saveResult = await self.coreDataWorker?.save(chars: chars) else { return }
            
            self.parse(result: saveResult)
            await MainActor.run {
                self.presenter?.addNew(chars: chars)               
            }
        }
    }
    
    func parse<T>(result: Result<T, Error>) -> T? {
        switch result {
        case .success(let value):
            return value
        case .failure(let error):
            DispatchQueue.main.async {
                self.presenter?.showAlert(type: .warning, text: TestError.text(from: error))
            }
            return nil
        }
    }
}
