//
//  MainRouter.swift
//  Simple
//
//  Created by Raymond Law on 6/25/18.
//  Copyright (c) 2018 Clean Swift LLC. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MainRoutingLogic {
    func showDetail(for item: CharacterModels.Char)
}

class MainRouter: NSObject, MainRoutingLogic {
    weak var viewController: MainViewController?

        
    func showDetail(for item: CharacterModels.Char) {
        let detailVC = DetailViewController(char: CharacterModels.Char)
        viewController?.navigationController?.pushViewController(detailVC, animated: true)
    }
}
