//
//  CharacterModels.swift
//  Simple
//
//  Created by Raymond Law on 6/25/18.
//  Copyright (c) 2018 Clean Swift LLC. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum CharacterModels {
    struct Response<T: Decodable>: Decodable {
        var info: Info
        var results: [T]
    }

    struct Info: Decodable {
        var count: Int
        var pages: Int
        var next: String?
        var prev: String?
    }

    struct Char: Decodable {
        var id: Int
        var name: String?
        var created: String?
        var gender: String?
        var image: String?
        
        var createdDate: Date? {
            guard let created else { return nil }
            return created.date(dateFormat: .full)
        }
    }
}
