//
//  MainPresenter.swift
//  Simple
//
//  Created by Raymond Law on 6/25/18.
//  Copyright (c) 2018 Clean Swift LLC. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MainPresentationLogic: BasePresentationLogic {
    func presentFromDB(cdChars: [CDCharacter])
    func addNew(chars: [Char])
}

class MainPresenter: MainPresentationLogic {
    weak var viewController: MainDisplayLogic?

    // MARK: Show greeting

    func presentFromDB(cdChars: [CDCharacter]) {
        let chars = convertToChars(cdChars: cdChars)
        
    }
    
    func addNew(chars: [Char]) {
        
    }
    
    private func convertToChars(cdChars: [CDCharacter]) -> [Char] {
        cdChars.map { cdChar in
            var char = Char(id: Int(cdChar.id))
            char.gender = cdChar.gender
            char.image = cdChar.image
            char.created = cdChar.created
            char.name = cdChar.name
            return char
        }
    }
}
