//
//  MainInteractor.swift
//  Simple
//
//  Created by Raymond Law on 6/25/18.
//  Copyright (c) 2018 Clean Swift LLC. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MainBusinessLogic {
    func showGreeting(request: Main.ShowGreeting.Request)
}

protocol MainDataStore {
}

class MainInteractor: MainBusinessLogic, MainDataStore {
    var presenter: MainPresentationLogic?

    // MARK: Show greeting

    func showGreeting(request: Main.ShowGreeting.Request) {
        //    let userID = AuthenticationWorker().getUserID()
        //    let response = Main.ShowGreeting.Response(userID: userID)
        //    presenter?.presentShowGreeting(response: response)
    }
}
