//
//  MainViewController.swift
//  Simple
//
//  Created by Raymond Law on 6/25/18.
//  Copyright (c) 2018 Clean Swift LLC. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import SnapKit


protocol MainDisplayLogic: AnyObject {
}


class MainViewController: BaseViewController, MainDisplayLogic {    
    var interactor: MainBusinessLogic?
    var router: (NSObjectProtocol & MainRoutingLogic & MainDataPassing)?

    // MARK: Setup
  
    override func setup() {
        let viewController = self
        let interactor = MainInteractor()
        let presenter = MainPresenter()
        let router = MainRouter()
        viewController.interactor = interactor
        viewController.router = router
        interactor.presenter = presenter
        presenter.viewController = viewController
        router.viewController = viewController
        router.dataStore = interactor
    }
  
    // MARK: View lifecycle

    override func viewDidLoad() {
        super.viewDidLoad()
        configureUI()
        //showGreeting()
    }

    // MARK: Show greeting

    private var greetingLabel: UILabel!

    private func configureUI() {
        view.backgroundColor = .yellow
        
        let view1 = UIView(frame: .init(x: 50, y: 50, width: 100, height: 100))
        view1.backgroundColor = .cyan
        view.addSubview(view1)
        
        view1.snp.makeConstraints { make in
            make.center.equalTo(CGPoint(x: 200, y: 200))
            make.size.equalTo(CGSize(width: 150, height: 100))
        }
    }
    
    override func updateViewConstraints() {
        super.updateViewConstraints()
    }
    
//    func showGreeting() {
//        let request = Main.ShowGreeting.Request()
//        interactor?.showGreeting(request: request)
//    }
//
//    func displayShowGreeting(viewModel: Main.ShowGreeting.ViewModel) {
//        if let userID = viewModel.userID {
//            greetingLabel.text = "Hello, \(userID)"
//        }
//    }
}
