//
//  MainViewController.swift
//  Simple
//
//  Created by Raymond Law on 6/25/18.
//  Copyright (c) 2018 Clean Swift LLC. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import SnapKit


protocol MainDisplayLogic: AnyObject {
    var chars: [Char] { set get }
    //func displayCharacters()
}


class MainViewController: BaseViewController, MainDisplayLogic {    
    var interactor: MainBusinessLogic?
    var router: (NSObjectProtocol & MainRoutingLogic & MainDataPassing)?
    
    var chars: [Char] = []

    // MARK: Setup
  
    override func setup() {
        let viewController = self
        let interactor = MainInteractor()
        let presenter = MainPresenter()
        let router = MainRouter()
        let worker = MainWorker()
        viewController.interactor = interactor
        viewController.router = router
        interactor.presenter = presenter
        interactor.coreDataWorker = worker
        interactor.apiWorker = worker
        presenter.viewController = viewController
        router.viewController = viewController
        router.dataStore = interactor
    }
  
    // MARK: View lifecycle

    override func viewDidLoad() {
        super.viewDidLoad()
        configureUI()
               
        interactor?.checkStateIsFirst()
    }

    // MARK: Show greeting

    private var greetingLabel: UILabel!

    private func configureUI() {
        view.backgroundColor = .yellow
        
        let view1 = UIButton(type: .system)
        view1.frame = .init(x: 50, y: 50, width: 100, height: 100)
        view1.backgroundColor = .cyan
        view1.addAction(UIAction(handler: {_ in
            AlertView.show(with: .warning, text: TestError.allDownload.text)
        }), for: .touchUpInside)
        view.addSubview(view1)
        
        view1.snp.makeConstraints { make in
            make.center.equalTo(CGPoint(x: 200, y: 200))
            make.size.equalTo(CGSize(width: 150, height: 100))
        }
    }
    
    override func updateViewConstraints() {
        super.updateViewConstraints()
    }
    
    func showCharacters() {
        //let request = Main.ShowGreeting.Request()
        interactor?.showFromDBCharacters()
    }
    
    
    func loadNextCharacters() {
        interactor?.loadNextCharacters()
    }
}
