//
//  MainInteractor.swift
//  Simple
//
//  Created by Raymond Law on 6/25/18.
//  Copyright (c) 2018 Clean Swift LLC. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MainBusinessLogic {
    func showFromDBCharacters()
    func loadNextCharacters()
}

protocol MainDataStore {
}

class MainInteractor: MainBusinessLogic, MainDataStore {
    var presenter: MainPresentationLogic?
    var coreDataWorker: CoreDataWorkerProtocol?
    var apiWorker: ApiWorkerProtocol?

    func showFromDBCharacters() {
        let result = coreDataWorker?.fetchAllChars()
        switch result {
        case .success(let chars):
            presenter?.presentFromDB(cdChars: chars)
        case .failure(let error):
            presenter?.showAlert(type: .warning, text: TestError.text(from: error))
        default: break
        }
    }
    
    func loadNextCharacters() {
        Task.detached {
            do {
                //let dd = try await self.api.next(type: Char.self)
            } catch {
                print(error.localizedDescription)
            }
        }
    }

    func showGreeting(request: Main.ShowGreeting.Request) {
        //    let userID = AuthenticationWorker().getUserID()
        //    let response = Main.ShowGreeting.Response(userID: userID)
        //    presenter?.presentShowGreeting(response: response)
    }
}
