//
//  DetailViewController.swift
//  Simple
//
//  Created by Raymond Law on 6/25/18.
//  Copyright (c) 2018 Clean Swift LLC. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit


class DetailViewController: BaseViewController {
    var char: CharacterModels.Char? {
        didSet {
            update()
        }
    }
    
    // MARK: View lifecycle -
    override func viewDidLoad() {
        super.viewDidLoad()
        configureUI()
    }
  
    // MARK: Privtes -
    private func configureUI() {
        
    }
    
    private func update() {
        guard let char else { return }
        navigationItem.title = char.name
    }
}
